# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manggu's
brief-intro: 삽질 전문가
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minsoo-jun.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username: minsoo.jun
github_username:  minsoo-jun
email: jamesa75@gmail.com
linkedIn_username:
dribbble_username:

description_footer: 한삽 한삽 정성을 드려서 파자

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: #hygblog
disqus_shortname: minsoo

# statistic analysis
google_analytics_id: UA-114909806-1

# Build settings
#markdown: kramdown

#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

theme: jekyll-theme-hacker